[package]
name = "pefbin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = {version="0.24.1",features = ["persistence"]}
egui_extras = {version="0.24.2",features = ["image"]}


